<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup><OutputType>Exe</OutputType><TargetFramework>net8.0</TargetFramework><Nullable>disable</Nullable><ImplicitUsings>enable</ImplicitUsings><NuGetAudit>false</NuGetAudit><NoWarn>CA1416;CS0067;CS0649</NoWarn></PropertyGroup>
  <ItemGroup>
    <Compile Include="../VHSCapture/FFmpeg.cs" Link="FFmpeg.cs" />
    <Compile Include="../VHSCapture/NoSignalDetector.cs" Link="NoSignalDetector.cs" />
    <Compile Include="../VHSCapture/AppSettings.cs" Link="AppSettings.cs" />
    <Compile Include="../VHSCapture/DShowProps.cs" Link="DShowProps.cs" />
    <PackageReference Include="NetMQ" Version="4.0.1.13" />
    <PackageReference Include="System.Drawing.Common" Version="8.0.0" />
  </ItemGroup>
</Project>
